"""Phase Options-1 — options_shadow_decision_log diagnostic table.

Append-only shadow log for the options paper-trading evaluator.
Records one row per (run_date, underlying, option_symbol) evaluated.
NEVER writes to options_paper_trade, paper_trade, paper_position,
or any execution surface. NEVER influences any trading decision.

Schema rules:
  * One row per (run_date, option_symbol) — UNIQUE constraint
    enables idempotent rerun via ON CONFLICT DO NOTHING.
  * `would_trade=true` rows pass every required filter; carry
    score + diagnostics.
  * `would_trade=false` rows record the first failing filter in
    `reason` and the per-filter pass flags so operators can see
    exactly which gate blocked.

Revision ID: 056_options_shadow
Revises: 055_phase_11z_macro_unk
"""

from __future__ import annotations

from alembic import op


revision = "056_options_shadow"
down_revision = "055_phase_11z_macro_unk"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.options_shadow_decision_log (
            id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_date           date NOT NULL,
            underlying_symbol  text NOT NULL,
            option_symbol      text NOT NULL,
            expiration         date NOT NULL,
            strike             numeric(12,4) NOT NULL,
            option_type        text NOT NULL,
            side               text NOT NULL,
            strategy_name      text NOT NULL,
            would_trade        boolean NOT NULL,
            reason             text NOT NULL,
            liquidity_pass     boolean NOT NULL,
            spread_pass        boolean NOT NULL,
            open_interest_pass boolean NOT NULL,
            volume_pass        boolean NOT NULL,
            greeks_pass        boolean NOT NULL,
            iv_rank_pass       boolean NOT NULL,
            risk_pass          boolean NOT NULL,
            score              numeric(20,6),
            diagnostics        jsonb NOT NULL DEFAULT '{}'::jsonb,
            created_at         timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ux_options_shadow_run_option
              UNIQUE (run_date, option_symbol),
            CONSTRAINT ck_options_shadow_option_type
              CHECK (option_type IN ('call', 'put')),
            CONSTRAINT ck_options_shadow_side
              CHECK (side IN ('buy', 'sell'))
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_options_shadow_run_date "
        "ON public.options_shadow_decision_log (run_date DESC)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_options_shadow_would_trade "
        "ON public.options_shadow_decision_log (would_trade, run_date DESC)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_options_shadow_underlying "
        "ON public.options_shadow_decision_log (underlying_symbol, run_date DESC)"
    )


def downgrade() -> None:
    op.execute(
        "DROP INDEX IF EXISTS public.ix_options_shadow_underlying"
    )
    op.execute(
        "DROP INDEX IF EXISTS public.ix_options_shadow_would_trade"
    )
    op.execute(
        "DROP INDEX IF EXISTS public.ix_options_shadow_run_date"
    )
    op.execute(
        "DROP TABLE IF EXISTS public.options_shadow_decision_log"
    )
