"""Phase 11Z — replay/recovery provenance manifest.

Adds a single mapping table (`replay_recovery_manifest`) so we can
distinguish rows generated by `scripts/replay_paper_execution_chain.py`
(or any future replay tool) from live/dev rows WITHOUT touching the
existing schemas of `account`, `paper_trade`, `paper_position`,
or `recommendation`.

Why a mapping table rather than `source` columns on each table:
    * No ALTER on hot tables (zero risk to live writes).
    * Tagging is opt-in: rows without a manifest entry are treated
      as 'live' by default at the API layer.
    * Easy to revoke a tag (delete one row) vs reverse a column.
    * Same shape covers any future replay (options, alerts, etc.).

Revision ID: 061_replay_manifest
Revises: 060_auth_sub_org
"""

from __future__ import annotations

from alembic import op


revision = "061_replay_manifest"
down_revision = "060_auth_sub_org"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.replay_recovery_manifest (
          id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
          created_at          timestamptz NOT NULL DEFAULT now(),
          replay_run_id       text NOT NULL,
          replay_generated_at timestamptz NOT NULL DEFAULT now(),
          entity_type         text NOT NULL,
          entity_id           text NOT NULL,
          source              text NOT NULL DEFAULT 'replay',
          notes               text,
          CONSTRAINT ux_replay_manifest_entity
            UNIQUE (entity_type, entity_id),
          CONSTRAINT ck_replay_manifest_entity_type
            CHECK (entity_type IN (
              'account','paper_portfolio','paper_trade',
              'paper_position','recommendation','recommendation_evidence',
              'paper_equity_snapshot'
            )),
          CONSTRAINT ck_replay_manifest_source
            CHECK (source IN ('live','dev','replay','test'))
        );
        CREATE INDEX IF NOT EXISTS ix_replay_manifest_run
          ON public.replay_recovery_manifest(replay_run_id);
        CREATE INDEX IF NOT EXISTS ix_replay_manifest_source
          ON public.replay_recovery_manifest(source);
        CREATE INDEX IF NOT EXISTS ix_replay_manifest_type
          ON public.replay_recovery_manifest(entity_type);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS public.replay_recovery_manifest;")
