"""M5 demand-validation feedback — integration tests (real Postgres + TestClient).

Drives the real app with get_session overridden to the test session. Verifies
the POST /api/feedback/signal endpoint for authenticated + anonymous callers,
validation, payload storage, and that no read endpoint exists.
"""

from __future__ import annotations

import uuid

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import text
from sqlalchemy.orm import Session

from apps.api.src.auth import identity as ident
from apps.api.src.db import get_session
from apps.api.src.main import app

pytestmark = pytest.mark.integration


def _ensure(db: Session) -> None:
    db.execute(text(
        """
        CREATE TABLE IF NOT EXISTS app_user (
            id text PRIMARY KEY, email text UNIQUE, display_name text,
            auth_provider text NOT NULL DEFAULT 'placeholder',
            external_auth_id text, password_hash text,
            created_at timestamptz NOT NULL DEFAULT now(), disabled_at timestamptz
        )
        """
    ))
    db.execute(text(
        """
        CREATE TABLE IF NOT EXISTS user_session (
            token text PRIMARY KEY,
            user_id text NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
            created_at timestamptz NOT NULL DEFAULT now(),
            expires_at timestamptz NOT NULL, revoked_at timestamptz
        )
        """
    ))
    db.execute(text(
        """
        CREATE TABLE IF NOT EXISTS user_feedback_signal (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id text REFERENCES app_user(id) ON DELETE SET NULL,
            session_or_device_id text,
            surface text NOT NULL,
            signal_type text NOT NULL,
            value text,
            payload jsonb,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    ))
    db.commit()


@pytest.fixture
def client(pg_session: Session):
    _ensure(pg_session)

    def _override():
        yield pg_session

    app.dependency_overrides[get_session] = _override
    try:
        yield TestClient(app)
    finally:
        app.dependency_overrides.pop(get_session, None)


def _make_user(db: Session) -> tuple[str, str]:
    uid = ident.create_user(db, email=f"f-{uuid.uuid4().hex[:10]}@example.com", password="password123")
    token = ident.create_session(db, uid)
    db.commit()
    return uid, token


def test_authenticated_signal_has_user_id(client, pg_session) -> None:
    uid, token = _make_user(pg_session)
    r = client.post(
        "/api/feedback/signal",
        json={"surface": "pick_detail", "signal_type": "trust_useful", "value": "yes"},
        cookies={"arthos_session": token},
    )
    assert r.status_code == 200 and r.json()["ok"] is True
    row = pg_session.execute(
        text("SELECT user_id, signal_type FROM user_feedback_signal WHERE user_id = :u ORDER BY id DESC LIMIT 1"),
        {"u": uid},
    ).mappings().first()
    assert row is not None and row["user_id"] == uid and row["signal_type"] == "trust_useful"


def test_anonymous_signal_has_no_user_id(client, pg_session) -> None:
    dev = "dev-" + uuid.uuid4().hex[:8]
    r = client.post(
        "/api/feedback/signal",
        json={"surface": "discover", "signal_type": "would_use_again"},
        headers={"X-Auth-User-Id": dev},
    )
    assert r.status_code == 200
    row = pg_session.execute(
        text("SELECT user_id, session_or_device_id FROM user_feedback_signal WHERE session_or_device_id = :d ORDER BY id DESC LIMIT 1"),
        {"d": dev},
    ).mappings().first()
    assert row is not None and row["user_id"] is None and row["session_or_device_id"] == dev


def test_invalid_signal_type_rejected(client) -> None:
    r = client.post("/api/feedback/signal", json={"surface": "pick_detail", "signal_type": "bogus"})
    assert r.status_code == 422


def test_invalid_surface_rejected(client) -> None:
    r = client.post("/api/feedback/signal", json={"surface": "bogus", "signal_type": "trust_useful"})
    assert r.status_code == 422


def test_payload_stored_safely(client, pg_session) -> None:
    marker = "mk-" + uuid.uuid4().hex[:8]
    r = client.post(
        "/api/feedback/signal",
        json={"surface": "profile", "signal_type": "feedback_text", "value": marker, "payload": {"a": 1, "b": "x"}},
    )
    assert r.status_code == 200
    row = pg_session.execute(
        text("SELECT payload FROM user_feedback_signal WHERE value = :v ORDER BY id DESC LIMIT 1"),
        {"v": marker},
    ).mappings().first()
    assert row is not None and row["payload"] == {"a": 1, "b": "x"}


def test_no_read_endpoint(client) -> None:
    # POST-only; there is no GET list endpoint that could expose other users' feedback.
    assert client.get("/api/feedback/signal").status_code in (404, 405)
    assert client.get("/api/feedback/signals").status_code in (404, 405)
