"""M1B login rate-limit / lockout — integration tests (real Postgres).

Exercises the rate-limit functions directly (no TestClient). The login_attempt
table is a raw-SQL migration table not in ORM create_all, so we ensure it here
idempotently. Each test uses a unique email so rows never collide.
"""

from __future__ import annotations

import uuid

import pytest
from sqlalchemy import text
from sqlalchemy.orm import Session

from apps.api.src.auth import identity as ident

pytestmark = pytest.mark.integration

MAX, WINDOW, LOCKOUT = 5, 900, 900


def _ensure(db: Session) -> None:
    db.execute(text(
        """
        CREATE TABLE IF NOT EXISTS login_attempt (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email text NOT NULL,
            ip text NOT NULL DEFAULT '',
            succeeded boolean NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    ))
    db.commit()


@pytest.fixture
def rl_db(pg_session: Session) -> Session:
    _ensure(pg_session)
    return pg_session


def _email() -> str:
    return f"rl-{uuid.uuid4().hex[:10]}@example.com"


def _fail(db: Session, email: str, *, secs_ago: float = 0, ip: str = "") -> None:
    db.execute(
        text(
            "INSERT INTO login_attempt (email, ip, succeeded, created_at) "
            "VALUES (:e, :ip, false, now() - make_interval(secs => :s))"
        ),
        {"e": email.lower(), "ip": ip, "s": float(secs_ago)},
    )


def _locked(db: Session, email: str, ip: str = "") -> bool:
    return ident.login_locked(
        db, email=email, ip=ip,
        max_attempts=MAX, window_seconds=WINDOW, lockout_seconds=LOCKOUT,
    )


def test_under_limit_not_locked(rl_db: Session) -> None:
    em = _email()
    for _ in range(MAX - 1):
        _fail(rl_db, em)
    rl_db.commit()
    assert _locked(rl_db, em) is False  # allowed attempts below the limit


def test_at_limit_locked(rl_db: Session) -> None:
    em = _email()
    for _ in range(MAX):
        _fail(rl_db, em)
    rl_db.commit()
    assert _locked(rl_db, em) is True  # blocked once limit reached


def test_locked_by_ip_across_emails(rl_db: Session) -> None:
    ip = "203.0.113." + str(uuid.uuid4().int % 250)
    for _ in range(MAX):
        _fail(rl_db, _email(), ip=ip)  # distinct emails, same IP
    rl_db.commit()
    # A fresh email from the same IP is locked (IP-based brute-force throttle).
    assert _locked(rl_db, _email(), ip=ip) is True


def test_success_resets_lock(rl_db: Session) -> None:
    em = _email()
    for _ in range(MAX):
        _fail(rl_db, em)
    rl_db.commit()
    assert _locked(rl_db, em) is True
    ident.clear_login_failures(rl_db, email=em)  # successful login resets
    rl_db.commit()
    assert _locked(rl_db, em) is False


def test_window_expiry_not_locked(rl_db: Session) -> None:
    em = _email()
    for _ in range(MAX):
        _fail(rl_db, em, secs_ago=WINDOW + 60)  # all older than the window
    rl_db.commit()
    assert _locked(rl_db, em) is False  # aged-out failures don't count


def test_lockout_expiry_not_locked(rl_db: Session) -> None:
    em = _email()
    # Failures within the counting window but last one older than the lockout.
    for _ in range(MAX):
        _fail(rl_db, em, secs_ago=5)
    rl_db.commit()
    assert ident.login_locked(
        rl_db, email=em, ip="", max_attempts=MAX, window_seconds=WINDOW, lockout_seconds=1,
    ) is False  # lockout elapsed → unlocked


def test_record_login_attempt_persists(rl_db: Session) -> None:
    em = _email()
    ident.record_login_attempt(rl_db, email=em, ip="198.51.100.7", succeeded=False)
    rl_db.commit()
    n = rl_db.execute(
        text("SELECT count(*) FROM login_attempt WHERE email = :e AND succeeded = false"),
        {"e": em},
    ).scalar()
    assert n == 1
