"""M5A — DB-backed tests for the demand-validation report (days filter + trend)."""

from __future__ import annotations

import uuid

import pytest
from sqlalchemy import text
from sqlalchemy.orm import Session

from apps.api.src.api.feedback_report import build_report, load_signals

pytestmark = pytest.mark.integration


def _ensure(db: Session) -> None:
    db.execute(text(
        """
        CREATE TABLE IF NOT EXISTS user_feedback_signal (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id text, session_or_device_id text,
            surface text NOT NULL, signal_type text NOT NULL,
            value text, payload jsonb,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    ))
    db.commit()


@pytest.fixture
def db(pg_session: Session) -> Session:
    _ensure(pg_session)
    return pg_session


def _insert(db: Session, signal_type: str, *, days_ago: float = 0, marker: str = "", user_id: str | None = None) -> None:
    db.execute(
        text(
            """
            INSERT INTO user_feedback_signal (user_id, session_or_device_id, surface, signal_type, value, created_at)
            VALUES (:uid, :dev, 'pick_detail', :st, :val, now() - make_interval(secs => :s))
            """
        ),
        {"uid": user_id, "dev": (None if user_id else "dev-" + marker), "st": signal_type, "val": marker, "s": float(days_ago) * 86400.0},
    )


def test_days_filter_works(db: Session) -> None:
    tag = uuid.uuid4().hex[:6]
    _insert(db, "trust_useful", days_ago=10, marker=f"old{tag}")
    _insert(db, "trust_useful", days_ago=1, marker=f"new{tag}")
    db.commit()
    all_rows = [r for r in load_signals(db) if str(r.get("value", "")).endswith(tag)]
    last7 = [r for r in load_signals(db, days=7) if str(r.get("value", "")).endswith(tag)]
    assert len(all_rows) == 2
    assert len(last7) == 1
    assert last7[0]["value"] == f"new{tag}"


def test_build_report_end_to_end_and_trend(db: Session) -> None:
    tag = uuid.uuid4().hex[:6]
    # Anonymous (device-context) inserts — avoids the app_user FK; authed-user
    # counting is covered by the pure unit test.
    _insert(db, "trust_useful", days_ago=1, marker=tag)
    _insert(db, "trust_not_useful", days_ago=1, marker=tag)
    _insert(db, "beta_interest", days_ago=1, marker=tag)
    db.commit()
    rep = build_report(db, days=30)
    assert rep["total_signals"] >= 3
    assert rep["beta_interest"] >= 1
    assert isinstance(rep["trend_7d"], list)
    assert rep["window_days"] == 30
