"""M1C auth ops — trusted client-IP resolution + login_attempt pruning.

resolve_client_ip is pure (no DB); prune tests use the real login_attempt
table (ensured idempotently here, as it's a raw-SQL migration table).
"""

from __future__ import annotations

import uuid

import pytest
from sqlalchemy import text
from sqlalchemy.orm import Session

from apps.api.src.auth import identity as ident

pytestmark = pytest.mark.integration

TRUSTED = "127.0.0.1/32,10.0.0.0/8"


# --- trusted client-IP (pure) ---------------------------------------------
def test_proxy_disabled_uses_direct_ip() -> None:
    ip = ident.resolve_client_ip(
        direct_ip="10.0.0.5", trust_enabled=False, trusted_cidrs=TRUSTED,
        forwarded_for="1.2.3.4", cf_connecting_ip="9.9.9.9",
    )
    assert ip == "10.0.0.5"  # forwarded headers ignored when trust disabled


def test_untrusted_direct_client_cannot_spoof() -> None:
    ip = ident.resolve_client_ip(
        direct_ip="203.0.113.50", trust_enabled=True, trusted_cidrs=TRUSTED,
        forwarded_for="1.2.3.4", cf_connecting_ip="9.9.9.9",
    )
    assert ip == "203.0.113.50"  # direct peer not a trusted proxy → header ignored


def test_trusted_proxy_passes_forwarded_client_ip() -> None:
    ip = ident.resolve_client_ip(
        direct_ip="10.0.0.1", trust_enabled=True, trusted_cidrs=TRUSTED,
        forwarded_for="198.51.100.7", cf_connecting_ip=None,
    )
    assert ip == "198.51.100.7"


def test_cf_connecting_ip_preferred() -> None:
    ip = ident.resolve_client_ip(
        direct_ip="10.0.0.1", trust_enabled=True, trusted_cidrs=TRUSTED,
        forwarded_for="198.51.100.7", cf_connecting_ip="198.51.100.99",
    )
    assert ip == "198.51.100.99"


def test_first_valid_forwarded_ip_used() -> None:
    ip = ident.resolve_client_ip(
        direct_ip="10.0.0.1", trust_enabled=True, trusted_cidrs=TRUSTED,
        forwarded_for="1.2.3.4, 10.0.0.1, 10.0.0.2", cf_connecting_ip=None,
    )
    assert ip == "1.2.3.4"  # original client is the first XFF entry


def test_malformed_or_empty_forwarded_falls_back() -> None:
    assert ident.resolve_client_ip(
        direct_ip="10.0.0.1", trust_enabled=True, trusted_cidrs=TRUSTED,
        forwarded_for="not-an-ip", cf_connecting_ip="garbage",
    ) == "10.0.0.1"
    assert ident.resolve_client_ip(
        direct_ip="10.0.0.1", trust_enabled=True, trusted_cidrs=TRUSTED,
        forwarded_for="", cf_connecting_ip=None,
    ) == "10.0.0.1"


# --- prune (DB) -----------------------------------------------------------
def _ensure(db: Session) -> None:
    db.execute(text(
        """
        CREATE TABLE IF NOT EXISTS login_attempt (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email text NOT NULL, ip text NOT NULL DEFAULT '',
            succeeded boolean NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    ))
    db.commit()


@pytest.fixture
def db(pg_session: Session) -> Session:
    _ensure(pg_session)
    return pg_session


def _insert(db: Session, email: str, *, days_ago: float) -> None:
    db.execute(
        text(
            "INSERT INTO login_attempt (email, ip, succeeded, created_at) "
            "VALUES (:e, '', false, now() - make_interval(secs => :s))"
        ),
        {"e": email, "s": float(days_ago) * 86400.0},
    )


def _count(db: Session, email: str) -> int:
    return db.execute(
        text("SELECT count(*) FROM login_attempt WHERE email = :e"), {"e": email}
    ).scalar()


def test_old_rows_pruned(db: Session) -> None:
    em = f"old-{uuid.uuid4().hex[:8]}"
    _insert(db, em, days_ago=10)
    db.commit()
    ident.prune_login_attempts(db, retention_days=7, min_keep_seconds=0)
    db.commit()
    assert _count(db, em) == 0


def test_recent_rows_retained(db: Session) -> None:
    em = f"new-{uuid.uuid4().hex[:8]}"
    _insert(db, em, days_ago=1)
    db.commit()
    ident.prune_login_attempts(db, retention_days=7, min_keep_seconds=0)
    db.commit()
    assert _count(db, em) == 1


def test_min_keep_protects_lockout_rows(db: Session) -> None:
    em = f"lock-{uuid.uuid4().hex[:8]}"
    for _ in range(5):
        _insert(db, em, days_ago=0)  # recent failures driving an active lockout
    db.commit()
    # Even with retention_days=0, the min-keep floor (window+lockout) protects them.
    ident.prune_login_attempts(db, retention_days=0, min_keep_seconds=900 + 900)
    db.commit()
    assert _count(db, em) == 5
    assert ident.login_locked(
        db, email=em, ip="", max_attempts=5, window_seconds=900, lockout_seconds=900,
    ) is True
