// Phase L UI-1 — ReasoningCard.
//
// Renders the deterministic reasoning envelope. Every visible word
// comes from the backend renderer (setup, thesis, uncertainty) OR
// from the locked operator-authored banner copy (honest-absence
// state). Frontend NEVER paraphrases.
//
// Variants:
//   novice    — setup + thesis + uncertainty only. No structured detail.
//   operator  — adds collapsible structured payload (skeleton id,
//               slot fills, invalidation vocab, envelope hash).
//
// Honest-absence policy: when the backend returns 404, we render
// the `incomplete_lifecycle` banner copy — never a substitute.

import { useState } from "react";

import { useEnvelope } from "@/lib/reasoning/useEnvelope";
import SourcePill from "./SourcePill";


// Locked operator-authored copy for the empty state. Mirrors the
// backend `truth_banners.py` incomplete_lifecycle text — kept in sync
// manually for now; UI-2 will source from the /system-state endpoint.
//
// Phase L UI-1 N.3 revision: "Part of this is still being built"
// reads as platform-incompleteness rather than deliberate restraint.
// Replaced with framing that names absence as a deliberate behavior.
//
// Semantic freeze pass (Phase B): all AI-attributing copy removed.
// Reasoning is generated by the deterministic backend renderer; when
// no envelope exists, the empty state must NOT invent prose about
// "the AI" — that violates the Phase L lock that every visible word
// of reasoning comes from the backend renderer. Empty-state copy
// now describes SYSTEM STATE (no envelope persisted for this row)
// rather than imputing thought to the AI.
const ABSENCE_SHORT = "No structured reasoning recorded";
const ABSENCE_LONG =
  "No reasoning envelope is recorded for this trade. The trade is in "
  + "your portfolio; the structured rationale is not available for it.";

const ABSENCE_RESEARCH_PREVIEW =
  "Research-stage signal — no trade has been opened yet. Structured "
  + "reasoning is recorded only after entry.";

const LOADING_LABEL = "Loading reasoning…";

const ERROR_HEAD = "The reasoning service didn't respond";
const ERROR_BODY =
  "Structured reasoning could not be loaded. The trade itself is "
  + "intact — only the rendered explanation is unavailable right now.";


export interface ReasoningCardProps {
  /** When provided, fetches the envelope from the backend. */
  paperTradeId: string | null | undefined;
  /** novice = no structured detail; operator = collapsible detail. */
  variant?: "novice" | "operator";
  /** When the parent knows there is no trade yet (e.g. research-stage
   *  pick), pass true to render the research-preview absence state
   *  without making a fetch. */
  researchPreview?: boolean;
  className?: string;
}


export default function ReasoningCard({
  paperTradeId, variant = "novice", researchPreview, className,
}: ReasoningCardProps) {
  const { loading, envelope, error } = useEnvelope(
    researchPreview ? null : paperTradeId,
  );

  const classes = [
    "reasoning-card",
    `reasoning-card-${variant}`,
    className ?? null,
  ].filter(Boolean).join(" ");

  // 1. Research-preview state — caller asserted there is no decision yet.
  if (researchPreview) {
    return (
      <section
        className={classes}
        data-test="reasoning-card"
        data-state="research_preview"
      >
        <header className="reasoning-card-header">
          <h4 className="reasoning-card-title">{ABSENCE_SHORT}</h4>
        </header>
        <p className="reasoning-card-body">{ABSENCE_RESEARCH_PREVIEW}</p>
      </section>
    );
  }

  // 2. No identifier — show research-preview state by default.
  if (!paperTradeId) {
    return (
      <section
        className={classes}
        data-test="reasoning-card"
        data-state="no_trade_id"
      >
        <header className="reasoning-card-header">
          <h4 className="reasoning-card-title">{ABSENCE_SHORT}</h4>
        </header>
        <p className="reasoning-card-body">{ABSENCE_RESEARCH_PREVIEW}</p>
      </section>
    );
  }

  // 3. Loading.
  if (loading) {
    return (
      <section
        className={classes}
        data-test="reasoning-card"
        data-state="loading"
      >
        <p className="reasoning-card-body u-mono-sm text-fg-2">{LOADING_LABEL}</p>
      </section>
    );
  }

  // 4. Error (non-404).
  if (error) {
    return (
      <section
        className={classes}
        data-test="reasoning-card"
        data-state="error"
      >
        <header className="reasoning-card-header">
          <h4 className="reasoning-card-title">{ERROR_HEAD}</h4>
        </header>
        <p className="reasoning-card-body">{ERROR_BODY}</p>
      </section>
    );
  }

  // 5. Honest absence — backend returned 404.
  if (!envelope) {
    return (
      <section
        className={classes}
        data-test="reasoning-card"
        data-state="honest_absence"
      >
        <header className="reasoning-card-header">
          <h4 className="reasoning-card-title">{ABSENCE_SHORT}</h4>
        </header>
        <p className="reasoning-card-body">{ABSENCE_LONG}</p>
      </section>
    );
  }

  // 6. Rendered envelope — server-rendered text only.
  const { rendered, envelope: env, skeleton_id, envelope_hash } = envelope;
  return (
    <section
      className={classes}
      data-test="reasoning-card"
      data-state="rendered"
      data-skeleton={skeleton_id}
    >
      <header className="reasoning-card-header">
        <SourcePill source={env.source} />
      </header>

      <p className="reasoning-card-setup">{rendered.setup}</p>
      <p className="reasoning-card-thesis">{rendered.thesis}</p>

      {rendered.uncertainty.length > 0 && (
        <ul className="reasoning-card-uncertainty">
          {rendered.uncertainty.map((line, i) => (
            <li key={i} className="reasoning-card-uncertainty-item">{line}</li>
          ))}
        </ul>
      )}

      {variant === "operator" && (
        <OperatorDetail
          skeletonId={skeleton_id}
          envelopeHash={envelope_hash}
          slotFills={env.slot_fills}
          invalidationVocab={env.invalidation.condition_vocab}
          uncertaintyMarkers={env.uncertainty_markers}
          horizon={env.thesis.horizon}
          expectedSignal={env.thesis.expected_signal}
        />
      )}
    </section>
  );
}


interface OperatorDetailProps {
  skeletonId: string;
  envelopeHash: string;
  slotFills: Record<string, string | string[]>;
  invalidationVocab: string;
  uncertaintyMarkers: string[];
  horizon: string;
  expectedSignal: string;
}


function OperatorDetail({
  skeletonId, envelopeHash, slotFills, invalidationVocab,
  uncertaintyMarkers, horizon, expectedSignal,
}: OperatorDetailProps) {
  const [open, setOpen] = useState(false);
  return (
    <details
      className="reasoning-card-detail"
      open={open}
      onToggle={(e) => setOpen((e.target as HTMLDetailsElement).open)}
    >
      <summary className="reasoning-card-detail-summary">
        Show structured data
      </summary>
      <dl className="reasoning-card-detail-list u-mono-sm">
        <dt>skeleton</dt>
        <dd>{skeletonId}</dd>
        <dt>horizon</dt>
        <dd>{horizon}</dd>
        <dt>expected_signal</dt>
        <dd>{expectedSignal}</dd>
        <dt>invalidation</dt>
        <dd>{invalidationVocab}</dd>
        {Object.entries(slotFills).map(([k, v]) => (
          <div key={k} className="reasoning-card-slot">
            <dt>{k}</dt>
            <dd>{Array.isArray(v) ? v.join(", ") : v}</dd>
          </div>
        ))}
        {uncertaintyMarkers.length > 0 && (
          <>
            <dt>markers</dt>
            <dd>{uncertaintyMarkers.join(", ")}</dd>
          </>
        )}
        <dt>envelope_hash</dt>
        <dd>{envelopeHash}</dd>
      </dl>
    </details>
  );
}
