// Phase 11W (Phase B) - client-side forbidden-token regex used by the
// fail-closed render guard. Mirrors the DB CHECK token list and adds
// the UX-extension list (Gemini contribution).
//
// If any of these substrings (word-boundary or phrase) appears in
// research artifact body text, the render guard replaces the panel
// with a standardised safety-failure block. This is defence in depth;
// the DB CHECK already rejects on insert.
//
// NEVER add code that "scrubs" or "redacts" the body silently.
// Always fail closed: render the safety message, log to ops, surface
// for review.

const ACTION_WORDS = [
  'buy', 'sell', 'hold', 'long', 'short',
  'recommend', 'recommends', 'recommended', 'recommending',
  'recommendation', 'recommendations',
  'signal', 'signals', 'signaled', 'signaling',
  'allocate', 'allocates', 'allocated', 'allocating', 'allocation',
  'execute', 'executes', 'executed', 'executing', 'execution',
  'position', 'positions', 'entry', 'exit',
  'leverage', 'leveraged', 'leveraging',
  'promote', 'promotes', 'promoted', 'promoting',
  'outperform', 'underperform',
];

// UX-extension list (not in DB CHECK because they're suggestive,
// not strictly action-emitting).
const UX_EXTENSIONS = [
  'bullish', 'bearish',
  'conviction', 'confident',
  'alpha', 'forecast', 'prediction', 'advice',
];

const FORBIDDEN_PHRASES = [
  /target\s+price/i,
  /stop[\s-]?loss/i,
  /take[\s-]?profit/i,
  /portfolio\s+manager/i,
  /copy[\s-]?trade/i,
  /trade\s+now/i,
  /best\s+trade/i,
  /position\s+size/i,
  /allocation\s*%/i,
];

const wordBoundaryRegex = (words: string[]): RegExp => {
  return new RegExp('\\b(' + words.join('|') + ')\\b', 'i');
};

const ACTION_REGEX = wordBoundaryRegex(ACTION_WORDS);
const UX_REGEX = wordBoundaryRegex(UX_EXTENSIONS);

export interface TokenScanResult {
  ok: boolean;
  matched?: string;
}

export const scanForbiddenTokens = (text: string): TokenScanResult => {
  if (!text) {
    return { ok: true };
  }
  const actionMatch = text.match(ACTION_REGEX);
  if (actionMatch) {
    return { ok: false, matched: actionMatch[1] };
  }
  const uxMatch = text.match(UX_REGEX);
  if (uxMatch) {
    return { ok: false, matched: uxMatch[1] };
  }
  for (const re of FORBIDDEN_PHRASES) {
    const m = text.match(re);
    if (m) {
      return { ok: false, matched: m[0] };
    }
  }
  return { ok: true };
};

export const RESEARCH_BANNER_TEXT =
  'Research note — not execution logic. Generated by an LLM. ' +
  'Not financial advice.';
